username: example@alijnmerchant.com
password: **********

positions:
  - Blockchain
  #- Software
  

locations:
  #- Canada
  - New York
  - Chicago
  - Los Angeles
  - Boston
  - Palo Alto
  - Austin
  - Menlo Park
  - Seattle
  - Denver
  - Atlanta
  - Sunnyvale
  - Mountain View
  - San Jose
  - Portlant
  - San Diego
  - Nashville
  - Oakland
  - Santa Clara
  - Washington DC
  - San Francisco
  #- Vancouver
  - Tampa
  #- Remote

# --------- Optional Parameters -------
uploads:
  Resume: /Users/aliasgarmerchant/Desktop/LinkedIn-Easy-Apply-Bot/Resume_A.pdf 
  Cover Letter: /Users/aliasgarmerchant/Desktop/LinkedIn-Easy-Apply-Bot/Cover_G.docx
  City: Jersey City, New Jersey, United States
#  Photo: # PATH TO photo


output_filename: output.csv

# blacklist:
# - # Company names you want to ignore
